services:
  postgres:
    container_name: database
    image: postgres:alpine3.13
    environment:
      POSTGRES_USER: upload
      POSTGRES_PASSWORD: start
      POSTGRES_DB: files_s3
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - upload-files
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: is@dev.com
      PGADMIN_DEFAULT_PASSWORD: start
    ports:
      - "5050:80"
    networks:
      - upload-files
    restart: unless-stopped

networks:
  upload-files:
    driver: bridge

volumes:
  postgres:
    driver: local